# agents/ceo_agent.py

import os
import json
import requests
from dotenv import load_dotenv
from message_bus import send_message, get_last_message, print_full_history

load_dotenv()  # loads all keys from .env file

# ─────────────────────────────────────────
# LLM HELPER FUNCTION
# This is how every agent talks to OpenRouter
# ─────────────────────────────────────────

def call_llm(system_prompt, user_prompt):
    response = requests.post(
        "https://openrouter.ai/api/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {os.getenv('OPENROUTER_API_KEY')}",
            "Content-Type": "application/json"
        },
        json={
            "model": "anthropic/claude-sonnet-4.6",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
        }
    )
    result = response.json()
    return result["choices"][0]["message"]["content"]


# ─────────────────────────────────────────
# PHASE 1 + 2: DECOMPOSE STARTUP IDEA INTO TASKS
# LLM generates tasks - nothing is hardcoded
# ─────────────────────────────────────────

def decompose_idea(startup_idea):
    """
    Uses LLM to break the startup idea into 3 tasks:
    one for Product agent, one for Engineer agent, one for Marketing agent.
    Returns a dictionary with tasks for each agent.
    """
    print("\n🧠 CEO: Decomposing startup idea into tasks...")

    system_prompt = """You are the CEO of a startup. You receive a startup idea and break it 
    into specific tasks for your team. You must return ONLY a valid JSON object with no 
    extra text, no markdown, no backticks. Just pure JSON."""

    user_prompt = f"""
    Startup idea: {startup_idea}
    
    Break this into exactly 3 tasks for these agents:
    1. product_agent: focused on defining users, features, and value proposition
    2. engineer_agent: focused on what to build for the landing page
    3. marketing_agent: focused on how to market and who to target
    
    Return ONLY this JSON structure:
    {{
        "product_agent": "specific task description for product agent",
        "engineer_agent": "specific task description for engineer agent", 
        "marketing_agent": "specific task description for marketing agent"
    }}
    """

    response = call_llm(system_prompt, user_prompt)

    # Parse the JSON response from LLM
    tasks = json.loads(response)
    print(f"✅ CEO: Tasks generated by LLM")
    return tasks


# ─────────────────────────────────────────
# PHASE 3: SEND TASKS TO AGENTS
# ─────────────────────────────────────────

def send_tasks(startup_idea, tasks):
    """
    Sends structured JSON task messages to each agent
    via the message bus
    """
    print("\n📤 CEO: Sending tasks to all agents...")

    # Send task to Product agent
    msg_to_product = send_message(
        from_agent="ceo",
        to_agent="product",
        message_type="task",
        payload={
            "idea": startup_idea,
            "task": tasks["product_agent"]
        }
    )

    # Send task to Engineer agent
    msg_to_engineer = send_message(
        from_agent="ceo",
        to_agent="engineer",
        message_type="task",
        payload={
            "idea": startup_idea,
            "task": tasks["engineer_agent"]
        }
    )

    # Send task to Marketing agent
    msg_to_marketing = send_message(
        from_agent="ceo",
        to_agent="marketing",
        message_type="task",
        payload={
            "idea": startup_idea,
            "task": tasks["marketing_agent"]
        }
    )

    return msg_to_product, msg_to_engineer, msg_to_marketing


# ─────────────────────────────────────────
# PHASE 4: REVIEW AGENT OUTPUT
# CEO uses LLM to decide if output is good enough
# This is the feedback loop the PDF requires
# ─────────────────────────────────────────

def review_output(agent_name, output, original_task):
    """
    Uses LLM to review an agent's output.
    Returns a dict with:
    - verdict: "approved" or "revision_needed"
    - feedback: specific feedback if revision needed
    """
    print(f"\n🔍 CEO: Reviewing {agent_name} output...")

    system_prompt = """You are a strict CEO reviewing your team's work. 
    You must return ONLY a valid JSON object with no extra text, no markdown, no backticks."""

    user_prompt = f"""
    You assigned this task to {agent_name}: {original_task}
    
    They produced this output: {json.dumps(output)}
    
    Review this output critically. Ask yourself:
    - Is it specific to the startup idea?
    - Is it complete and detailed enough?
    - Does it actually address the task?
    
    Return ONLY this JSON:
    {{
        "verdict": "approved" or "revision_needed",
        "feedback": "specific feedback if revision needed, empty string if approved",
        "reasoning": "brief explanation of your decision"
    }}
    """

    response = call_llm(system_prompt, user_prompt)
    review = json.loads(response)

    print(f"   Verdict: {review['verdict']}")
    print(f"   Reasoning: {review['reasoning']}")

    return review


# ─────────────────────────────────────────
# SEND REVISION REQUEST
# If CEO is not satisfied, it sends revision_request back
# ─────────────────────────────────────────

def send_revision_request(agent_name, feedback, parent_message_id):
    """
    Sends a revision request back to an agent
    with specific feedback from the CEO's LLM review
    """
    print(f"\n🔄 CEO: Sending revision request to {agent_name}...")

    send_message(
        from_agent="ceo",
        to_agent=agent_name,
        message_type="revision_request",
        payload={
            "feedback": feedback,
            "instruction": f"Please revise your output based on this feedback: {feedback}"
        },
        parent_message_id=parent_message_id
    )


# ─────────────────────────────────────────
# POST FINAL SUMMARY TO SLACK
# ─────────────────────────────────────────

def post_final_summary_to_slack(startup_idea, product_spec, pr_url):
    """
    Posts a final summary to Slack #launches channel
    using Block Kit formatting as required by PDF
    """
    print("\n📢 CEO: Posting final summary to Slack...")

    token = os.getenv("SLACK_BOT_TOKEN")

    payload = {
        "channel": "#launches",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🚀 LaunchMind: New Startup Launched!"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Startup Idea:* {startup_idea}"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Value Proposition:* {product_spec.get('value_proposition', 'N/A')}"
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*GitHub PR:* <{pr_url}|View Pull Request>"
                    },
                    {
                        "type": "mrkdwn",
                        "text": "*Status:* ✅ All agents completed"
                    }
                ]
            }
        ]
    }

    response = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={"Authorization": f"Bearer {token}"},
        json=payload
    )

    result = response.json()
    if result["ok"]:
        print("✅ CEO: Final summary posted to Slack!")
    else:
        print(f"❌ CEO: Slack post failed: {result['error']}")


# ─────────────────────────────────────────
# MAIN CEO FUNCTION
# This is what gets called from main.py
# ─────────────────────────────────────────

def run_ceo(startup_idea):
    """
    Main function that runs the entire CEO agent lifecycle
    """
    print("\n" + "="*50)
    print("🤖 CEO AGENT STARTING")
    print("="*50)
    print(f"Startup idea: {startup_idea}")

    # Phase 1+2: Decompose idea into tasks using LLM
    tasks = decompose_idea(startup_idea)

    # Phase 3: Send tasks to all agents
    msg_to_product, msg_to_engineer, msg_to_marketing = send_tasks(startup_idea, tasks)

    # Log the decisions made
    print("\n📋 CEO Decision Log:")
    print(f"   - Generated tasks using LLM (not hardcoded)")
    print(f"   - Sent task to Product agent: {tasks['product_agent'][:50]}...")
    print(f"   - Sent task to Engineer agent: {tasks['engineer_agent'][:50]}...")
    print(f"   - Sent task to Marketing agent: {tasks['marketing_agent'][:50]}...")

    return tasks, msg_to_product, msg_to_engineer, msg_to_marketing
