# agents/ceo_agent.py

import os
import json
import requests
from dotenv import load_dotenv
from message_bus import send_message, get_last_message, print_full_history, call_llm, call_llm_json

load_dotenv()

CEO_MODEL = "anthropic/claude-sonnet-4"


# ─────────────────────────────────────────
# PHASE 1 + 2: DECOMPOSE STARTUP IDEA
# ─────────────────────────────────────────

def decompose_idea(startup_idea):
    print("\n🧠 CEO: Decomposing startup idea into tasks...")

    system_prompt = """You are the CEO of a startup. You receive a startup idea and break it
    into specific tasks for your team. You must return ONLY a valid JSON object with no
    extra text, no markdown, no backticks. Just pure JSON."""

    user_prompt = f"""
    Startup idea: {startup_idea}

    Break this into exactly 3 tasks for these agents:
    1. product_agent: focused on defining users, features, and value proposition
    2. engineer_agent: focused on what to build for the landing page
    3. marketing_agent: focused on how to market and who to target

    Return ONLY this JSON structure:
    {{
        "product_agent": "specific task description for product agent",
        "engineer_agent": "specific task description for engineer agent",
        "marketing_agent": "specific task description for marketing agent"
    }}
    """

    tasks = call_llm_json(CEO_MODEL, system_prompt, user_prompt)
    print(f"✅ CEO: Tasks generated by LLM")
    return tasks


# ─────────────────────────────────────────
# PHASE 3: SEND TASKS TO AGENTS
# ─────────────────────────────────────────

def send_tasks(startup_idea, tasks):
    print("\n📤 CEO: Sending tasks to all agents...")

    msg_to_product = send_message(
        from_agent="ceo",
        to_agent="product",
        message_type="task",
        payload={
            "idea": startup_idea,
            "task": tasks["product_agent"]
        }
    )

    msg_to_engineer = send_message(
        from_agent="ceo",
        to_agent="engineer",
        message_type="task",
        payload={
            "idea": startup_idea,
            "task": tasks["engineer_agent"]
        }
    )

    msg_to_marketing = send_message(
        from_agent="ceo",
        to_agent="marketing",
        message_type="task",
        payload={
            "idea": startup_idea,
            "task": tasks["marketing_agent"]
        }
    )

    return msg_to_product, msg_to_engineer, msg_to_marketing


# ─────────────────────────────────────────
# PHASE 4: REVIEW AGENT OUTPUT
# ─────────────────────────────────────────

def review_output(agent_name, output, original_task):
    print(f"\n🔍 CEO: Reviewing {agent_name} output...")

    system_prompt = """You are a strict CEO reviewing your team's work.
    You must return ONLY a valid JSON object with no extra text, no markdown, no backticks."""

    user_prompt = f"""
    You assigned this task to {agent_name}: {original_task}

    They produced this output: {json.dumps(output)}

    Review this output critically. Ask yourself:
    - Is it specific to the startup idea?
    - Is it complete and detailed enough?
    - Does it actually address the task?

    Return ONLY this JSON:
    {{
        "verdict": "approved" or "revision_needed",
        "feedback": "specific feedback if revision needed, empty string if approved",
        "reasoning": "brief explanation of your decision"
    }}
    """

    review = call_llm_json(CEO_MODEL, system_prompt, user_prompt)
    print(f"   Verdict: {review['verdict']}")
    print(f"   Reasoning: {review['reasoning']}")
    return review


# ─────────────────────────────────────────
# SEND REVISION REQUEST
# ─────────────────────────────────────────

def send_revision_request(agent_name, feedback, parent_message_id):
    print(f"\n🔄 CEO: Sending revision request to {agent_name}...")

    send_message(
        from_agent="ceo",
        to_agent=agent_name,
        message_type="revision_request",
        payload={
            "feedback": feedback,
            "instruction": f"Please revise your output based on this feedback: {feedback}"
        },
        parent_message_id=parent_message_id
    )


# ─────────────────────────────────────────
# POST FINAL SUMMARY TO SLACK
# ─────────────────────────────────────────

def post_final_summary_to_slack(startup_idea, product_spec, pr_url):
    print("\n📢 CEO: Posting final summary to Slack...")

    token = os.getenv("SLACK_BOT_TOKEN")

    payload = {
        "channel": "#launches",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🚀 LaunchMind: New Startup Launched!"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Startup Idea:* {startup_idea}"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Value Proposition:* {product_spec.get('value_proposition', 'N/A')}"
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*GitHub PR:* <{pr_url}|View Pull Request>"
                    },
                    {
                        "type": "mrkdwn",
                        "text": "*Status:* ✅ All agents completed"
                    }
                ]
            }
        ]
    }

    response = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={"Authorization": f"Bearer {token}"},
        json=payload
    )

    result = response.json()
    if result["ok"]:
        print("✅ CEO: Final summary posted to Slack!")
    else:
        print(f"❌ CEO: Slack post failed: {result['error']}")


# ─────────────────────────────────────────
# MAIN CEO FUNCTION
# ─────────────────────────────────────────

def run_ceo(startup_idea):
    print("\n" + "="*50)
    print("🤖 CEO AGENT STARTING")
    print("="*50)
    print(f"Startup idea: {startup_idea}")

    tasks = decompose_idea(startup_idea)
    msg_to_product, msg_to_engineer, msg_to_marketing = send_tasks(startup_idea, tasks)

    print("\n📋 CEO Decision Log:")
    print(f"   - Generated tasks using LLM (not hardcoded)")
    print(f"   - Sent task to Product agent: {tasks['product_agent'][:50]}...")
    print(f"   - Sent task to Engineer agent: {tasks['engineer_agent'][:50]}...")
    print(f"   - Sent task to Marketing agent: {tasks['marketing_agent'][:50]}...")

    return tasks, msg_to_product, msg_to_engineer, msg_to_marketing